name: 'Verify and Release'

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    types: [ opened, reopened, synchronize ]

jobs:
  security-gates:
    uses: Trendyol/security-actions/.github/workflows/security-gates.yml@master
    permissions:
      actions: read
      contents: read
      security-events: write
  release:
    uses: trendyol/nest-swagger-checker-lint/.github/workflows/release.yml@main
    needs: security-gates
    secrets: inherit
